"set background=dark
"set t_Co=16
"hi Normal guibg=NONE ctermbg=NONE

syntax on
filetype plugin indent on

set encoding=utf-8
set mouse=a
set nocompatible
set splitbelow splitright
set autoindent
set smartindent
set noexpandtab
set tabstop=4
set softtabstop=0
set shiftwidth=4
set lazyredraw
set wildmenu
set wildmode=longest,list,full
set ignorecase
set smartcase
set showmatch
set showcmd
set ruler
set number
set showcmd
set foldenable
set foldmethod=marker

